---
title: "Complete list of publications"
format: pdf
---

1.  Alvarez TM, Liberato MV, Cairo JP, Paixão DA, Campos BM, [**Ferreira MR**]{.underline}, Almeida RF, Pereira IO, Bernardes A, Ematsu GC, Chinaglia M, Polikarpov I, de Oliveira Neto M, Squina FM. *A Novel Member of GH16 Family Derived from Sugarcane Soil Metagenome*. Appl Biochem Biotechnol. 2015 Sep;177(2):304-17. doi: [10.1007/s12010-015-1743-7](https://www.doi.org/10.1007/s12010-015-1743-7). Epub 2015 Aug 5. PMID: 26242386.

2.  Bezerra F, [**Ferreira MR**]{.underline}, Fontes GN, da Costa Fernandes CJ, Andia DC, Cruz NC, da Silva RA, Zambuzzi WF. *Nano hydroxyapatite-blasted titanium surface affects pre-osteoblast morphology by modulating critical intracellular pathways*. Biotechnol Bioeng. 2017 Aug;114(8):1888-1898. doi: [10.1002/bit.26310](https://www.doi.org/10.1002/bit.26310). Epub 2017 Jun 7. PMID: 28401535.

3.  Fernandes CJC, Bezerra F, [**Ferreira MR**]{.underline}, Andrade AFC, Pinto TS, Zambuzzi WF. *Nano hydroxyapatite-blasted titanium surface creates a biointerface able to govern Src-dependent osteoblast metabolism as prerequisite to ECM remodeling*. Colloids Surf B Biointerfaces. 2018 Mar 1;163:321-328. doi: [10.1016/j.colsurfb.2017.12.049](https://www.doi.org/10.1016/j.colsurfb.2017.12.049). Epub 2017 Dec 28. PMID: 29329077.

4.  da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Bezerra FJB, Zambuzzi WF. *Zirconia stimulates ECM-remodeling as a prerequisite to pre-osteoblast adhesion/proliferation by possible interference with cellular anchorage*. J Mater Sci Mater Med. 2018 Mar 26;29(4):41. doi: [10.1007/s10856-018-6041-9](https://www.doi.org/10.1007/s10856-018-6041-9). PMID: 29582191.

5.  da Silva RA, de Camargo Andrade AF, da Silva Feltran G, Fernandes CJDC, de Assis RIF, [**Ferreira MR**]{.underline}, Andia DC, Zambuzzi WF. *The role of triiodothyronine hormone and mechanically-stressed endothelial cell paracrine signalling synergism in gene reprogramming during hBMSC-stimulated osteogenic phenotype in vitro*. Mol Cell Endocrinol. 2018 Dec 15;478:151-167. doi: [10.1016/j.mce.2018.08.008](https://www.doi.org/10.1016/j.mce.2018.08.008). Epub 2018 Aug 22. PMID: 30142372.

6.  da Silva Feltran G, da Costa Fernandes CJ, [**Rodrigues Ferreira M**]{.underline}, Kang HR, de Carvalho Bovolato AL, de Assis Golim M, Deffune E, Koh IHJ, Constantino VRL, Zambuzzi WF. *Sonic hedgehog drives layered double hydroxides-induced acute inflammatory landscape*. Colloids Surf B Biointerfaces. 2019 Feb 1;174:467-475. doi: [10.1016/j.colsurfb.2018.11.051](https://www.doi.org/10.1016/j.colsurfb.2018.11.051). Epub 2018 Nov 22. PMID: 30497008.

7.  Machado MIP, Gomes AM, [Rodrigues MF]{.underline}[^1] , Silva Pinto T, da Costa Fernandes CJ, Bezerra FJ, Zambuzzi WF. *Cobalt-chromium-enriched medium ameliorates shear-stressed endothelial cell performance*. J Trace Elem Med Biol. 2019 Jul;54:163-171. doi: [10.1016/j.jtemb.2019.04.012](https://www.doi.org/10.1016/j.jtemb.2019.04.012). Epub 2019 Apr 24. PMID: 31109607.

8.  da S Feltran G, Bezerra F, da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Zambuzzi WF. *Differential inflammatory landscape stimulus during titanium surfaces obtained osteogenic phenotype*. J Biomed Mater Res A. 2019 Aug;107(8):1597-1604. doi: [10.1002/jbm.a.36673](https://www.doi.org/10.1002/jbm.a.36673). Epub 2019 Apr 9. PMID: 30884166.

9.  da Silva RA, Fuhler GM, Janmaat VT, da C Fernandes CJ, da Silva Feltran G, Oliveira FA, Matos AA, Oliveira RC, [**Ferreira MR**]{.underline}, Zambuzzi WF, Peppelenbosch MP. *HOXA cluster gene expression during osteoblast differentiation involves epigenetic contro*l. Bone. 2019 Aug;125:74-86. doi: [10.1016/j.bone.2019.04.026](https://www.doi.org/10.1016/j.bone.2019.04.026). Epub 2019 May 1. PMID: 31054377.

10. da Silva RA, [**Ferreira MR**]{.underline}, Gomes AM, Zambuzzi WF. *LncRNA HOTAIR is a novel endothelial mechanosensitive gene*. J Cell Physiol. 2020 May;235(5):4631-4642. doi: [10.1002/jcp.29340](https://www.doi.org/10.1002/jcp.29340). Epub 2019 Oct 21. PMID: 31637716.

11. Gomes OP, Feltran GS, [**Ferreira MR**]{.underline}, Albano CS, Zambuzzi WF, Lisboa-Filho PN. *A novel BSA immobilizing manner on modified titanium surface ameliorates osteoblast performance*. Colloids Surf B Biointerfaces. 2020 Jun;190:110888. doi: [10.1016/j.colsurfb.2020.110888](https://www.doi.org/10.1016/j.colsurfb.2020.110888). Epub 2020 Feb 20. PMID: 32114272.

12. da Silva RA, da Silva Feltran G, [**Ferreira MR**]{.underline}, Wood PF, Bezerra F, Zambuzzi WF. *The Impact of Bioactive Surfaces in the Early Stages of Osseointegration: An \<i\>In Vitro\</i\> Comparative Study Evaluating the HAnano® and SLActive® Super Hydrophilic Surfaces*. Biomed Res Int. 2020 Sep 13;2020:3026893. doi: [10.1155/2020/3026893](https://www.doi.org/10.1155/2020/3026893). PMID: 33005686; PMCID: PMC7509554.

13. [**Ferreira MR**]{.underline}, Milani R, Rangel EC, Peppelenbosch M, Zambuzzi W. *OsteoBLAST: Computational Routine of Global Molecular Analysis Applied to Biomaterials Development*. Front Bioeng Biotechnol. 2020 Oct 8;8:565901. doi: [10.3389/fbioe.2020.565901](https://www.doi.org/10.3389/fbioe.2020.565901). PMID: 33117780; PMCID: PMC7578266.

14. Assis RIF, Feltran GDS, Silva MES, Palma ICDR, Rovai ES, Miranda TB, [**Ferreira MR**]{.underline}, Zambuzzi WF, Birbrair A, Andia DC, da Silva RA. *Non-coding RNAs repressive role in post-transcriptional processing of RUNX2 during the acquisition of the osteogenic phenotype of periodontal ligament mesenchymal stem cells*. Dev Biol. 2021 Feb;470:37-48. doi: [10.1016/j.ydbio.2020.10.012](https://www.doi.org/10.1016/j.ydbio.2020.10.012). Epub 2020 Nov 2. PMID: 33152274.

15. [**Ferreira MR**]{.underline}, Santos GA, Biagi CA, Silva Junior WA, Zambuzzi WF. *GSVA score reveals molecular signatures from transcriptomes for biomaterials comparison*. J Biomed Mater Res A. 2021 Jun;109(6):1004-1014. doi: [10.1002/jbm.a.37090](https://www.doi.org/10.1002/jbm.a.37090). Epub 2020 Sep 9. PMID: 32820608.

16. [**Ferreira MR**]{.underline}, Zambuzzi WF. *Platelet microparticles load a repertory of miRNAs programmed to drive osteogenic phenotype*. J Biomed Mater Res A. 2021 Aug;109(8):1502-1511. doi: [10.1002/jbm.a.37140](https://www.doi.org/10.1002/jbm.a.37140). Epub 2020 Dec 10. PMID: 33258548.

17. Pinto TS, Martins BR, [**Ferreira MR**]{.underline}, Bezerra F, Zambuzzi WF. *Nanohydroxyapatite-Blasted Bioactive Surface Drives Shear-Stressed Endothelial Cell Growth and Angiogenesis*. Biomed Res Int. 2022 Feb 23;2022:1433221. doi: [10.1155/2022/1433221](https://www.doi.org/10.1155/2022/1433221). PMID: 35252440; PMCID: PMC8890866.

18. Franco Cairo JPL, Mandelli F, Tramontina R, Cannella D, Paradisi A, Ciano L, [**Ferreira MR**]{.underline}, Liberato MV, Brenelli LB, Gonçalves TA, Rodrigues GN, Alvarez TM, Mofatto LS, Carazzolle MF, Pradella JGC, Paes Leme AF, Costa-Leonardo AM, Oliveira-Neto M, Damasio A, Davies GJ, Felby C, Walton PH, Squina FM. *Oxidative cleavage of polysaccharides by a termite-derived \<i\>superoxide dismutase\</i\> boosts the degradation of biomass by glycoside hydrolases*. Green Chem. 2022 May 12;24(12):4845-4858. doi: [10.1039/d1gc04519a](https://www.doi.org/10.1039/d1gc04519a). PMID: 35813357; PMCID: PMC9208272.

19. da C Fernandes CJ, da Silva RAF, de Almeida GS, [**Ferreira MR**]{.underline}, de Morais PB, Bezerra F, Zambuzzi WF. Epigenetic *Differences Arise in Endothelial Cells Responding to Cobalt-Chromium*. J Funct Biomater. 2023 Feb 26;14(3):127. doi: [10.3390/jfb14030127](https://www.doi.org/10.3390/jfb14030127). PMID: 36976051; PMCID: PMC10052026.

20. Fernandes CJDC, da Silva RAF, Wood PF, [**Ferreira MR**]{.underline}, de Almeida GS, de Moraes JF, Bezerra FJ, Zambuzzi WF. *Titanium-Enriched Medium Promotes Environment-Induced Epigenetic Machinery Changes in Human Endothelial Cells*. J Funct Biomater. 2023 Feb 27;14(3):131. doi: [10.3390/jfb14030131](https://www.doi.org/10.3390/jfb14030131). PMID: 36976055; PMCID: PMC10055987.

21. da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Zambuzzi WF. *Cyclopamine targeting hedgehog modulates nuclear control of the osteoblast activity*. Cells Dev. 2023 Jun;174:203836. doi: [10.1016/j.cdev.2023.203836](https://www.doi.org/10.1016/j.cdev.2023.203836). Epub 2023 Mar 25. PMID: 36972848.

22. Amadeu de Oliveira F, Tokuhara CK, Veeriah V, Domezi JP, Santesso MR, Cestari TM, Ventura TMO, Matos AA, Dionísio T, [**Ferreira MR**]{.underline}, Ortiz RC, Duarte MAH, Buzalaf MAR, Ponce JB, Sorgi CA, Faccioli LH, Buzalaf CP, de Oliveira RC. The *Multifarious Functions of Leukotrienes in Bone Metabolism*. J Bone Miner Res. 2023 Aug;38(8):1135-1153. doi: [10.1002/jbmr.4867](https://www.doi.org/10.1002/jbmr.4867). Epub 2023 Jun 29. PMID: 37314430.

23. Carvalho LB, Dos Santos Sanna PL, Dos Santos Afonso CC, Bondan EF, da Silva Feltran G, [**Ferreira MR**]{.underline}, Birbrair A, Andia DC, Latini A, Foganholi da Silva RA. *MicroRNA biogenesis machinery activation and lncRNA and REST overexpression as neuroprotective responses to fight inflammation in the hippocampus*. J Neuroimmunol. 2023 Sep 15;382:578149. doi: [10.1016/j.jneuroim.2023.578149](https://doi.org/10.1016/j.jneuroim.2023.578149). Epub 2023 Jul 18. PMID: 37481910.

24. Bergamo ETP, Balderrama ÍF, [**Ferreira MR**]{.underline}, Spielman R, Slavin BV, Torroni A, Tovar N, Nayak VV, Slavin BR, Coelho PG, Witek L. *Osteogenic differentiation and reconstruction of mandible defects using a novel resorbable membrane: An in vitro and in vivo experimental study*. J Biomed Mater Res B Appl Biomater. 2023 Nov;111(11):1966-1978. doi: [10.1002/jbm.b.35299](https://doi.org/10.1002/jbm.b.35299). Epub 2023 Jul 20. PMID: 37470190.

25. de Almeida GS, [**Ferreira MR**]{.underline}, da Costa Fernandes CJ, Suter LC, Carra MGJ, Correa DRN, Rangel EC, Saeki MJ, Zambuzzi WF. *Development of cobalt (Co)-doped monetites for bone regeneration*. J Biomed Mater Res B Appl Biomater. 2024 Jan;112(1):e35319. doi: [10.1002/jbm.b.35319](https://www.doi.org/10.1002/jbm.b.35319). Epub 2023 Aug 23. PMID: 37610175.

26. de Almeida GS, [**Ferreira MR**]{.underline}, Fernandes CC Jr, de Biagi CAO Jr, Silva WA Jr, Rangel EC, Lisboa-Filho PN, Zambuzzi WF. *Combination of in silico and cell culture strategies to predict biomaterial performance: Effects of sintering temperature on the biological properties of hydroxyapatite*. J Biomed Mater Res B Appl Biomater. 2024 Feb;112(2):e35389. doi: [10.1002/jbm.b.35389](https://www.doi.org/10.1002/jbm.b.35389). PMID: 38356168.

27. Lemes Dos Santos Sanna P, Bernardes Carvalho L, Cristina Dos Santos Afonso C, de Carvalho K, Aires R, Souza J, [**Rodrigues Ferreira M**]{.underline}, Birbrair A, Martha Bernardi M, Latini A, Foganholi da Silva RA. *Adora2A downregulation promotes caffeine neuroprotective effect against LPS-induced neuroinflammation in the hippocampus*. Brain Res. 2024 Jun 15;1833:148866. doi: [10.1016/j.brainres.2024.148866](https://www.doi.org/10.1016/j.brainres.2024.148866). Epub 2024 Mar 15. PMID: 38494098.

28. da Silva Feltran G, Augusto da Silva R, da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Dos Santos SAA, Justulin Junior LA, Del Valle Sosa L, Zambuzzi WF. *Vascular smooth muscle cells exhibit elevated hypoxia-inducible Factor-1α expression in human blood vessel organoids, influencing osteogenic performance*. Exp Cell Res. 2024 Jul 15;440(2):114136. doi: [10.1016/j.yexcr.2024.114136](https://www.doi.org/10.1016/j.yexcr.2024.114136). Epub 2024 Jun 22. PMID: 38909881.

29. Fernandes CJC, Silva RA, [**Ferreira MR**]{.underline}, Fuhler GM, Peppelenbosch MP, van der Eerden BC, Zambuzzi WF. *Vascular smooth muscle cell-derived exosomes promote osteoblast-to-osteocyte transition via β-catenin signaling*. Exp Cell Res. 2024 Sep 1;442(1):114211. doi: [10.1016/j.yexcr.2024.114211](https://www.doi.org/10.1016/j.yexcr.2024.114211). Epub 2024 Aug 14. PMID: 39147261.

30. Naia Fioretto M, Maciel FA, Barata LA, Ribeiro IT, Basso CBP, [**Ferreira MR**]{.underline}, Dos Santos SAA, Mattos R, Baptista HS, Portela LMF, Padilha PM, Felisbino SL, Scarano WR, Zambrano E, Justulin LA. *Impact of maternal protein restriction on the proteomic landscape of male rat lungs across the lifespan*. Mol Cell Endocrinol. 2024 Oct 1;592:112348. doi: [10.1016/j.mce.2024.112348](https://www.doi.org/10.1016/j.mce.2024.112348). Epub 2024 Aug 31. PMID: 39218056.

31. [**Ferreira MR**]{.underline}, Carratto TMT, Frontanilla TS, Bonadio RS, Jain M, de Oliveira SF, Castelli EC, Mendes-Junior CT. *Advances in forensic genetics: Exploring the potential of long read sequencing*. Forensic Sci Int Genet. 2025 Jan;74:103156. doi: [10.1016/j.fsigen.2024](https://www.doi.org/10.1016/j.fsigen.2024).103156. Epub 2024 Oct 10. PMID: 39427416.

32. L Urbano Pagan, M Gatto, [**MR Ferreira**]{.underline}, MJ Gomes, JPG Oliveira, GAF Mota, FC Damatto, LM Souza, ACC Santos, EA Rodrigues, PA Borim, DHS Campos, MP Okoshi, K Okoshi. *Effects of empagliflozin on myocardial transcriptome in rats with aortic stenosis-induced heart failure*. European Heart Volume 45, Issue Supplement_1, October 2024, ehae666.1829. doi: [10.1093/eurheartj/ehae6](https://doi.org/10.1093/eurheartj/ehae666.1829)

33. Castelli EC, Pereira RN, Paes GS, Andrade HS, [**Ferreira MR**]{.underline}, de Freitas Santos ÍS, Vince N, Pollock NR, Norman PJ, Meyer D. *kir-mapper: A Toolkit for Killer-Cell Immunoglobulin-Like Receptor (KIR) Genotyping From Short-Read Second-Generation Sequencing Data*. HLA. 2025 Mar;105(3):e70092. doi: [10.1111/tan.70092](https://www.doi.org/). PMID: 40095784; PMCID: PMC11927768.

34. Zambuzzi WF, [**Ferreira MR**]{.underline}. *Dynamic ion-releasing biomaterials actively shape the microenvironment to enhance healing*. J Trace Elem Med Biol. 2025 Jun;89:127657. doi: [10.1016/j.jtemb.2025.127657](https://www.doi.org/10.1016/j.jtemb.2025.127657). Epub 2025 Apr 17. PMID: 40250222.

35. Zambuzzi WF, [**Ferreira MR**]{.underline}, Wang Z, Peppelenbosch MP. *A Biochemical View on Intermittent Fasting's Effects on Human Physiology-Not Always a Beneficial Strategy*. Biology (Basel). 2025 Jun 9;14(6):669. doi: [10.3390/biology14060669](https://www.doi.org/10.3390/biology14060669). PMID: 40563920; PMCID: PMC12190167.

36. [**Ferreira MR**]{.underline}, Feltran GDS, Gomes AM, Vieira JCS, Santana GG, Silva MA, Santos EAAD, Zambuzzi WF. *Mesenchymal Stem Cell Differentiation Induced by Lyophilized PRP During Early Osteogenesis*. Cell Biol Int. 2026 Jan;50(1):e70101. doi: [10.1002/cbin.70101](https://www.doi.org/10.1002/cbin.70101). Epub 2025 Nov 13. PMID: 41230788.

[^1]: There was an error in the submission, resulting in the reversal of the surnames. Therefore, the correct name is Marcel Rodrigues Ferreira. If you wish to confirm the accuracy of this article, please consult Professor Dr. Willian Zambuzzi ([w.zambuzzi\@unesp.br](mailto:w.zambuzzi@unesp.br)).
